import { createClient } from "@/lib/database/server";
import Link from "next/link";

export default async function HomePage() {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <div className="max-w-4xl w-full text-center space-y-8">
      <div className="space-y-4">
        <p className="text-xl md:text-2xl text-gray-600 max-w-2xl mx-auto">
          Learn faster with smart flash-cards generated by AI
        </p>
      </div>

      <div className="grid md:grid-cols-3 gap-6 mt-12">
        <div className="bg-white p-6 rounded-lg shadow-md">
          <div className="text-4xl mb-4">🧠</div>
          <h3 className="text-lg font-semibold mb-2">Customised AI</h3>
          <p className="text-gray-600">
            Automatic flashcards generation, adapted to your level
          </p>
        </div>

        <div className="bg-white p-6 rounded-lg shadow-md">
          <div className="text-4xl mb-4">📊</div>
          <h3 className="text-lg font-semibold mb-2">Smart follow-up</h3>
          <p className="text-gray-600">
            Spaced repetition algorithm to optimise your memorization
          </p>
        </div>

        <div className="bg-white p-6 rounded-lg shadow-md">
          <div className="text-4xl mb-4">🌍</div>
          <h3 className="text-lg font-semibold mb-2">Multi-Domains</h3>
          <p className="text-gray-600">
            Languages, sciences, health... Learn what suits you the most
          </p>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mt-12">
        {user ? (
          <Link
            href="/dashboard"
            className="px-8 py-3 bg-indigo-600 text-white font-semibold rounded-lg hover:bg-indigo-700 transition-colors shadow-lg"
          >
            Go to my decks
          </Link>
        ) : (
          <>
            <Link
              href="/login"
              className="px-8 py-3 bg-indigo-600 text-white font-semibold rounded-lg hover:bg-indigo-700 transition-colors shadow-lg"
            >
              Log in
            </Link>
            <Link
              href="/waitlist"
              className="px-8 py-3 bg-purple-600 text-white font-semibold rounded-lg hover:bg-indigo-700 transition-colors shadow-lg"
            >
              Join the waiting list
            </Link>
          </>
        )}

        <Link
          href="/about"
          className="px-8 py-3 bg-white text-indigo-600 font-semibold rounded-lg hover:bg-gray-50 transition-colors shadow-md border border-indigo-200"
        >
          Learn more
        </Link>
      </div>
    </div>
  );
}
